  ![jupyter](img/itq.png )

<div align="center">

#  PAO25-26- NumPy

</div>

**Nombre:** *Maiccol Zurita*  
**Fecha:** *16/01/2026*


  ![jupyter](img/python.png )


# NumPy ndarray

* NumPy (Num erical Py thon) es la de facto librería estándar para análisis numérico en
Python
* Estructura de datos multidimensional eficiente (escrita en C): ndarray
* Colección de funciones para álgebra lineal, estadística descriptiva
* Ayuda al procesamiento de datos (np.where)


In [1]:
#importar libreria
import numpy as np

**2.1 Performance Sample, NumPy vs Plain Python**

In [3]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 594 ms
Wall time: 584 ms


In [4]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 516 ms
Wall time: 516 ms


**2.2 Formas de crear ndarrays**

In [5]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [6]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [7]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [8]:
# Generar arrays con valores fijos
print(np.zeros(2)) # 1D
print(np.ones((4,3))) # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**2.3 Obtener información sobre ndarray**

In [9]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)


[ 2 71  0 34]


In [11]:
print(my_ndarray.argmax()) # índice del valor más alto
print(np.amax(my_ndarray))
print(my_ndarray.argmin()) # índice del valor más bajo
print(np.amin(my_ndarray))
print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [12]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones


[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [13]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

4
(4,)
1


**Redimensionar los datos**

In [14]:
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]]) # matrix 1x8
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim)

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [15]:
new_dims = my_ndarray.reshape(2, 4) # cambiar las dimensiones a 2x4
print(new_dims)
print(new_dims.ndim)

[[  0  71  21  19]
 [213 412 111  98]]
2


In [16]:
new_dims = my_ndarray.reshape(4, 2) # cambiar las dimensiones a 4x2
print(new_dims)
print(new_dims.ndim)

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [17]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [18]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten())


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [19]:
 # reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2,-1)) # el segundo valor se infiere del primero


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


**2.4 Manipulación de ndarrays**

In [20]:
# Cambiar ejes
new_dims = np.arange(16).reshape(8,2)
print(new_dims)
print(new_dims.swapaxes(0,1))


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [21]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims, axis = None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [22]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)


[ 2  9 10 17]


In [23]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]
print(np.hstack((a1,a2))) # una al lado de la otra
print(np.hstack((a1,a2)).shape)
print(np.vstack((a1,a2))) # una encima de la otra
print(np.vstack((a1,a2)).shape)


[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [24]:
array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[3, 5], [7, 9]])
print(np.concatenate((array1, array2), axis = 0))


[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [25]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, 2, axis = 0)) # divide array en 2 partes iguales
print(np.array_split(array, 3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [26]:
 # dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, [3], axis = 1)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [27]:
split = np.array_split(array, [3], axis = 1)
print(split[0][3][0])


12


In [29]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0)) # divide array por la fila 1 y 3
print(np.array_split(array, [1, 3], axis = 1)) # divide array por la columna 1␣ y 3
# axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

# Índices y slicing

* De manera análoga a índices y slicing para listas

In [30]:
array = np.arange(10, 16)
print(array)
print(array[-1]) # acceso unidimensional
print(array[:-1]) # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [31]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [32]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])
print(array[1][2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


**NumPy es row major**

In [33]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3) # by default, row major
print(row_major)


[[1 2 3]
 [4 5 6]]


In [34]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C') # by default, row major
print(row_major)
col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F') # col major
print(col_major)


[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


**Slice**

In [35]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[1:3, 2::2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [36]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0,:])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


**Diferencias entre índices y slicing en listas y ndarrays:**

* ¡Retornan una referencia, no una copia!

In [37]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2] # devuelve una copia
print(my_copy)
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [38]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5] # devuelve una referencia
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [39]:
 # copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy() # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


* Permite asignar valores a un corte

In [40]:
array = np.arange(10)
print(array)
print(array[0:3])
array[0:3] = -1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


* Slicing condicionales (mask)

In [41]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array %2 == 0
print(mask)
print(array[mask])
print(array[array %2 == 0])
array[mask] = 0
print(array)


[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [42]:
array = np.arange(-3,4)
print(array)
array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [43]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array % 2 == 0
print(mask)
array_par = array[mask] # devuelve una copia
print(array_par)
array_par[0] = -10
print(array)
print(array_par)


[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


*  Acceso a múltiples valores con listados de índices


In [45]:
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[[1,2]]) #selecting rows
print(array[:,[1,2]]) #selecting columns
# cross product of indexes
print(array[[1,2],:][:,[1,2]])
print(array[np.ix_([1,2],[1,2])]) # built in ix_
ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Funciones matemáticas

* Aplicar operaciones entre escalares y arrays o entre arrays

In [46]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)
lista += [1]
print(lista)


[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [47]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8)
print(array)
array *= 2
print(array)
array += 10
print(array)
print(array.dtype) # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [48]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1
print(array_1)
print(array_2)
print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_2 / array_1)


[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


**4.1 Broadcasting**
  
Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
                                                                                           

**4.2 Operadores unarios y binarios**

| Tipo    | Operación                                   | Descripción |
|---------|---------------------------------------------|-------------|
| Unario  | abs                                         | Valor absoluto de cada elemento |
| Unario  | sqrt                                        | Raíz cuadrada de cada elemento |
| Unario  | exp                                         | e^x, siendo x cada elemento |
| Unario  | log / log10 / log2                          | Logaritmos en distintas bases de cada elemento |
| Unario  | sign                                        | Retorna el signo de cada elemento (-1 negativo, 0 o 1 positivo) |
| Unario  | ceil                                        | Redondea cada elemento por arriba |
| Unario  | floor                                       | Redondea cada elemento por abajo |
| Unario  | isnan                                       | Retorna si cada elemento es NaN |
| Unario  | cos / sin / tan                             | Operaciones trigonométricas en cada elemento |
| Unario  | arccos / arcsin / arctan                   | Inversas de operaciones trigonométricas |
| Binario | add                                         | Suma de dos arrays |
| Binario | subtract                                   | Resta de dos arrays |
| Binario | multiply                                   | Multiplicación de dos arrays |
| Binario | divide                                      | División de dos arrays |
| Binario | maximum / minimum                           | Retorna el valor máximo/mínimo de cada pareja de elementos |
| Binario | equal / not_equal                           | Comparación de igualdad o diferencia |
| Binario | greater / greater_equal / less / less_equal| Comparaciones >, >=, <, <= |


In [49]:
# ejemplos de operadores
array = np.arange(5)
print(array)
np.sqrt(array)


[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [50]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])
print(array1)
print(array2)
print(np.greater(array1,array2))
print(np.less(array2, array1))


[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


# Estadística descriptiva

* Importante saber la naturaleza de los datos
* Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|--------|-------------|
| sum(arr) | Suma de todos los elementos de `arr` |
| mean(arr) | Media aritmética de los elementos de `arr` |
| std(arr) | Desviación estándar de los elementos de `arr` |
| cumsum(arr) | Devuelve un array con la suma acumulada de cada elemento con todos los anteriores |
| cumprod(arr) | Devuelve un array con el producto acumulado de cada elemento con todos los anteriores |
| min(arr), max(arr) | Mínimo y máximo de `arr` |
| any(arr) | En arrays booleanos, retorna `True` si algún elemento es `True` |
| all(arr) | En arrays booleanos, retorna `True` si todos los elementos son `True` (o ≠ 0 en valores numéricos) |
| unique(arr) | Devuelve un array con valores únicos |
| in1d(arr1, arr2) | Devuelve un array booleano indicando si cada elemento de `arr1` está en `arr2` |
| union1d(arr1, arr2) | Devuelve la unión de ambos arrays |
| intersect1d(arr1, arr2) | Devuelve la intersección de ambos arrays |


In [52]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [53]:
 # any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores␣<> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [54]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


# Álgebra lineal

* numpy.linalg contiene funciones para álgebra lineal
* dot product, multiplicación de matrices, cálculo del determinante, factorizaciones…

| Función | Descripción |
|--------|-------------|
| dot(mat1, mat2) | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| matmul(mat1, mat2) | Devuelve el producto entre dos matrices |
| trace(mat) | Suma de los elementos de la diagonal principal de la matriz |
| det(mat) | Devuelve el determinante de la matriz |
| eig(mat) | Computa los autovalores y autovectores de la matriz cuadrada `mat` |
| inv(mat) | Devuelve la inversa de la matriz |
| qr(mat) | Computa la factorización QR de `mat` |
| solve(A, b) | Resuelve el sistema lineal de ecuaciones `Ax = b`, cuando `A` es una matriz cuadrada |
| transpose(mat) | Devuelve la transpuesta de la matriz |


In [55]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)
print(A)
print(B)
print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [57]:
import numpy.linalg as lg
import math
# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x
a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])
print(a)
print(b)
x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')
print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


# Filtrado de datos

* Filtrar y modificar datos numéricos con np.where
* Retorna A o B en función de una condición en una array


In [60]:
import numpy as np

# Array de precios
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])

# Máscara booleana: elementos menores que 1
mask = prices < 1
print("Mask (prices < 1):")
print(mask)

# Slicing condicional
print("\nPrecios menores que 1:")
print(prices[prices < 1])

# Máscara usando np.where
mask = np.where(prices < 1, True, False)
print("\nMask con np.where:")
print(mask)

# Filtrado usando la máscara
print("\nPrecios usando la máscara:")
print(prices[mask])

# Reemplazar valores menores que 1 por 1.0 (modifica el array)
prices[mask] = 1.0
print("\nArray modificado:")
print(prices)

# Alternativa sin modificar el array original
print("\nUsando np.where sin modificar el array:")
print(np.where(prices < 1, 1.0, prices))


Mask (prices < 1):
[ True False False False  True]

Precios menores que 1:
[0.99 0.49]

Mask con np.where:
[ True False False False  True]

Precios usando la máscara:
[0.99 0.49]

Array modificado:
[ 1.   14.49 19.99 20.99  1.  ]

Usando np.where sin modificar el array:
[ 1.   14.49 19.99 20.99  1.  ]


In [63]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)


[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [64]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)
print(id(data))
print(id(data_clean))

[  10.   12. -143.    0.    1.   -3.]
1811527130496
1811527178096


In [66]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
credits = np.where(bank_transfers_values > 0) # array de índices para los que␣la condición es True
print(credits)
print(bank_transfers_values[credits]) # es igual que␣bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])


[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [67]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)
rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)
daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)
final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)


[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios

* Python módulo random

In [68]:
import random
print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores


0.857547606268915
0
1.963092179574767


In [69]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)


'Eevee'

**8.1 NumPy.random**

* Generar fácilmente listas con valores aleatorios

In [71]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las␣dimensiones)


0.616288467836669
2
[[0 2 2 0]
 [1 1 0 1]]


In [72]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[-1.08835331  0.57926034]
 [ 1.3303954   0.01809562]
 [ 1.56360047  0.74263864]
 [-0.07687905  0.50209738]]


In [74]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias␣

1
7.934610595211095
[[2 1]
 [1 5]]


**8..2 Random seed**
    
* Números pseudo-aleatorios
* Ordenadores generan números a partir de ecuaciones
* Basadas en un número inicial (seed)
* Bueno para reproducibilidad de experimentos

In [76]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())
print()
for i in range(6):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())


0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


#  Escritura y lectura de ndarrays a archivos

* Para futuro acceso
* C=ompartir datos con otros
* Formato *.npy


In [81]:
import numpy as np
import os

# Crear la ruta del directorio
ruta_dir = "res"
ruta_archivo = os.path.join(ruta_dir, "o_values_array.npy")

# Crear el directorio si no existe
os.makedirs(ruta_dir, exist_ok=True)

# Crear array aleatorio 3x3 con valores entre 0 y 8
values = np.random.randint(9, size=(3, 3))

# Guardar el array en archivo .npy
np.save(ruta_archivo, values)

# Mostrar el array
print(values)


[[2 4 6]
 [3 3 2]
 [1 5 7]]


In [82]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)


[[2 4 6]
 [3 3 2]
 [1 5 7]]


In [83]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")
values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz


In [86]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)
print(type(npzfile.files))
print(npzfile.files)
for key in npzfile.files: # array.files contiene el nombre de las arrays␣(arr_0, arr_1...)
    print(npzfile[key])

<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[4 3 1]
 [7 3 1]
 [5 7 0]]
[[2 2]
 [2 3]]
[[ 9  6 15  0]
 [ 5  2 13 11]
 [ 8 13  6 11]
 [ 8 15  0 12]]


**9.0.1 ¿Por qué molestarse con .npy?**

* Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
* ¿Para qué escribir los datos de nuevo?

In [95]:
import os
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)


FileNotFoundError: [Errno 2] No such file or directory: 'res\\fdata.csv'

In [97]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)


FileNotFoundError: [Errno 2] No such file or directory: 'res\\fdata.csv'

In [98]:
%%timeit
data = np.load(ruta_npy)


FileNotFoundError: [Errno 2] No such file or directory: 'res\\o_fdata.npy'

In [99]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")


FileNotFoundError: [Errno 2] No such file or directory: 'res\\fdata.csv'

**9.0.2 velocidad + simplicidad vs memoria**
    
**9.1 Ejercicios**


**100 numpy exercises**

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the initialise.py module, then for each question you can query the answer or an hint with hint(n) or answer(n) for n question number.


In [9]:
import os
os.getcwd()
os.listdir()


['.git',
 '.ipynb_checkpoints',
 'img',
 'introducciónpython.ipynb',
 'PAO25_25_02.ipynb',
 'PAO25_25_03.ipynb',
 'PAO25_25_04.ipynb',
 'PAO25_25_06.ipynb',
 'repaso.ipynb']

In [14]:
!jupyter nbconvert --to script initialise.ipynb


[NbConvertApp] Converting notebook initialise.ipynb to script
[NbConvertApp] Writing 186 bytes to initialise.py


In [16]:
import os
print("Directorio actual:")
print(os.getcwd())

print("\nArchivos .py visibles:")
print([f for f in os.listdir() if f.endswith(".py")])


Directorio actual:
C:\Users\maicc\Desktop\maiccol\machine2026

Archivos .py visibles:
['initialise.py']


In [20]:
!cd


C:\Users\maicc\Desktop\maiccol\machine2026


In [ ]:
!notepad initialise.py


In [1]:
!type initialise.py


In [3]:
%run initialise.py

In [4]:
!dir

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: E656-C58B

 Directorio de C:\Users\maicc\Desktop\maiccol\machine2026

17/01/2026  18:29    <DIR>          .
15/01/2026  11:31    <DIR>          ..
17/01/2026  18:29    <DIR>          .ipynb_checkpoints
07/01/2026  17:59    <DIR>          img
17/01/2026  18:27                 0 initialise.py
07/01/2026  18:05            15.459 introducciónpython.ipynb
08/01/2026  16:03           100.932 PAO25_25_02.ipynb
14/01/2026  15:10            52.754 PAO25_25_03.ipynb
14/01/2026  17:05            43.990 PAO25_25_04.ipynb
17/01/2026  18:29            78.381 PAO25_25_06.ipynb
15/01/2026  10:07            28.510 repaso.ipynb
               7 archivos        320.026 bytes
               4 dirs  90.692.157.440 bytes libres


In [5]:
%%writefile initialise.py
print("Archivo initialise.py ejecutado correctamente")


Overwriting initialise.py


In [6]:
!type initialise.py


print("Archivo initialise.py ejecutado correctamente")


In [7]:
%run initialise.py


Archivo initialise.py ejecutado correctamente


In [8]:
!type initialise.py


print("Archivo initialise.py ejecutado correctamente")


In [9]:
%run initialise.py


Archivo initialise.py ejecutado correctamente


**1. Import the numpy package under the name np (★☆☆)**

In [12]:
import numpy as np


In [13]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

**2. Print the numpy version and the configuration (★☆☆)**

In [15]:
import numpy as np

print(np.__version__)
np.show_config()


2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hn7iyo7q/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hn7iyo7q/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hn7iyo7q/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hn7iyo7q/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

**4. How to find the memory size of any array (★☆☆)**

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a.nbytes)


40


**6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [17]:
import numpy as np

v = np.zeros(10)
v[4] = 1

print(v)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**8. Reverse a vector (first element becomes last) (★☆☆)**


In [18]:
import numpy as np

v = np.array([1, 2, 3, 4, 5])
v_rev = v[::-1]

print(v_rev)


[5 4 3 2 1]


**10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)**

In [19]:
import numpy as np

a = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(a)

print(indices)


(array([0, 1, 4]),)


**12. Create a 3x3x3 array with random values (★☆☆)**



In [20]:
import numpy as np

a = np.random.random((3, 3, 3))
print(a)


[[[0.4693955  0.26661059 0.39151235]
  [0.7615751  0.25503174 0.6115861 ]
  [0.03619694 0.14117343 0.18737153]]

 [[0.90874183 0.21203036 0.75785451]
  [0.83017646 0.46656151 0.15868986]
  [0.86994958 0.79592225 0.76078872]]

 [[0.11435631 0.1646492  0.61346978]
  [0.27994692 0.34241033 0.06970446]
  [0.73676859 0.71704858 0.34429607]]]


**14. Create a random vector of size 30 and find the mean value (★☆☆)**



In [21]:
import numpy as np

v = np.random.random(30)
mean_value = v.mean()

print(mean_value)


0.5609175395157567


**16. How to add a border (filled with 0's) around an existing array? (★☆☆)**

In [22]:
import numpy as np

a = np.ones((3, 3))
bordered = np.pad(a, pad_width=1, mode='constant', constant_values=0)

print(bordered)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

In [23]:
import numpy as np

a = np.diag([1, 2, 3, 4], k=-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)**

In [24]:
import numpy as np

index = np.unravel_index(99, (6, 7, 8))
print(index)


(np.int64(1), np.int64(5), np.int64(3))


[https://github.com/Maick721/machin2026.git](https://github.com/Maick721/machin2026.git)